# Generated by Django 3.2.3 on 2021-07-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut')),
                ('fotografia', models.ImageField(upload_to='fotos')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('direccion', models.CharField(max_length=30, verbose_name='direccion')),
                ('email', models.CharField(max_length=25, verbose_name='email')),
                ('pais', models.CharField(max_length=25, verbose_name='pais')),
                ('password', models.CharField(max_length=25, verbose_name='password')),
            ],
        ),
    ]
